### ISSUE TITLE
Complete Client side application code

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#11]
DoD

- [x] Integrate the Client code with the Face Recognition Module for face comparison
- [x] Integrate the Door Lock/Unlock and Intrusion Detection with the Client Code using GPIO interfacing code before. 

Blockers: None

**Comment by harshberiwal** [comment]
- Updated the Face Recognition python code to compare unknown faces with known faces. 
- Interfaced the Relay and the LED with the Client code by using pigpiod. 
The commit for this can be found[ here](https://github.com/cu-ecen-aeld/final-project-harshberiwal/commit/d63dbd20ced521abcf1b0bf9ee262b1ff1cae135)

![Image](https://user-images.githubusercontent.com/111919475/235382212-2515008a-fdbb-4ffe-b5d4-412221cf721b.png)


![Image](https://user-images.githubusercontent.com/111919475/235382473-5539f8c7-7f7d-4030-91ef-9479c6e0663f.png)


![Image](https://user-images.githubusercontent.com/111919475/235382464-da2b3cef-c411-4aa1-8d95-3e9778fdcd37.png)
