### ISSUE TITLE
Automate the server and client

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#13]
DoD:
- [x]  Automate server and client by init scripts and interface camera code with server
- [x]  Debug/modify init scripts to run the server and client executables automatically at startup
Blockers: None

**Comment by harshberiwal** [comment]
- Updated the Makefile in Buildroot to generate a init module for both server and client executables.



![Image](https://user-images.githubusercontent.com/111919475/235384619-6a89fbac-51c6-41ad-842e-5d4b94667ee6.png)



- Automated the camera scripts so the whole system work without any human intervention.  



![Image](https://user-images.githubusercontent.com/111919475/235384577-c3e17d91-74e1-4178-b012-b8e05884ac83.png)


![Image](https://user-images.githubusercontent.com/111919475/235384716-53cdd107-62b5-4ab5-a694-e3769d48aead.png)


The commit to this is [here](https://github.com/cu-ecen-aeld/final-project-shashankchandrasekaran/commit/4ef38ab27722cbe5def4036a85ee0498d2221759)
