### ISSUE TITLE
Camera Interfacing

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#2]
DoD:

- [x] Downloading the Logitech Camera Module as an external package on Buildroot
- [x] Capture image and successfully store in Raspberry Pi 

Blockers: 

- Unable to test camera interfacing with Raspberry Pi due to the blocker in OpenCV.

**Comment by harshberiwal** [comment]
- Install packages for interfacing the Logitech C270 camera.(

![Image](https://user-images.githubusercontent.com/111919475/232396307-28d549dd-8c8c-420a-bed6-7abc45b8e11b.png)

)

- Blockers as OpenCV is causing the camera module to not be tested as given in the link below. 
https://github.com/shashankchandrasekaran/final-project-assignment-shashankchandrasekaran/issues/3#issuecomment-1510728603

**Comment by harshberiwal** [comment]
- Able to capture image using /home /capture command


![Image](https://user-images.githubusercontent.com/111919475/232424830-bdb178e4-0293-4034-a671-98473cab3a81.jpeg)

- Able to see the image using fbv command 

![Image](https://user-images.githubusercontent.com/111919475/232424934-a6844f6d-8f2e-48c1-8ea0-4f3d12d5af7f.jpeg)

The commit can be found [here](https://github.com/harshberiwal/AESD_Final_Project/commit/e4366e10df0304ddae95e52edd66fe6f33af114e)
