### ISSUE TITLE
OpenCV setup

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#3]
- [x] Installing and configuring openCV on Buildroot
- [x] Downloading necessary image processing libraries
- [x] Able to Boot Raspberry Pi 3b with OpenCV and Camera Drivers

Blockers: 

- Installed OpenCV on Buildroot but unable to boot the image later on Raspberry Pi 4

**Comment by harshberiwal** [comment]
- Used the below link for OpenCV Installation on Buildroot for Raspberry Pi 4 https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/OpenCV-3-Setup-in-Buildroot

- Followed all the steps here https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/OpenCV-3-Setup-in-Buildroot#:~:text=Repository%20setup,Your%20Image%20section 

- Obtained the sdcard.img file. 

- Flashed it onto the SDcard and when I boot my Rpi 4

- Unable to get the Buildroot login Prompt and getting an error of Requiring Newer Image after Booting as shown in the image Below.

![Image](https://user-images.githubusercontent.com/111919475/232390914-4efdbf15-6fb4-4995-bc74-4e7319227712.jpeg)

**Comment by harshberiwal** [comment]
The commit is [here](https://github.com/harshberiwal/AESD_Final_Project/commit/80d6f1bcbf7b787cd39bed530ed92e8675152bbd)

**Comment by harshberiwal** [comment]
- Solved the problem by making changes to shared.sh. It worked for Raspberry Pi 3B but didn't for Raspberry Pi 4. Changed the shared.sh to install post scripts and image as per Rpi 3B. 

- System boot-up with OpenCV and Camera Drivers 

![Image](https://user-images.githubusercontent.com/111919475/232424031-69f46e09-0c0c-4e4d-820d-dd1383a07011.jpeg)

The commit can be found[ here](https://github.com/harshberiwal/AESD_Final_Project/commit/e4366e10df0304ddae95e52edd66fe6f33af114e)
