### ISSUE TITLE
GPIO interfacing with Socket Client Raspberry Pi 

### ISSUE THREAD

**Issue by shashankchandrasekaran** [shashankchandrasekaran/final-project-assignment-shashankchandrasekaran#8]
DoD

- [x] Running the GPIO write code on Raspbian OS 
- [x] Installing the necessary GPIO Modules on Buildroot 
- [x] Integrated with Socket Client and turned the LED and Relay ON when client receives the image 

Blockers: None

**Comment by harshberiwal** [comment]
1. Was able to toggle an LED by testing the GPIO code on Raspbian. 


![Image](https://user-images.githubusercontent.com/111919475/233905820-e28a5512-c251-43fa-a9b3-bc471e788a6a.png)

2. Installed all the packages to interface the GPIO with Buildroot

![Image](https://user-images.githubusercontent.com/111919475/233905900-64207069-c258-43e0-88a5-fc6aa60d557c.png)

3. Integrated the GPIO code for LED and Relay with Socket Client when it receives an image. 


![Image](https://user-images.githubusercontent.com/111919475/233906124-f9eb3934-24d9-4fba-bf36-fc124c6d6302.png)


The commit is [here](https://github.com/cu-ecen-aeld/final-project-harshberiwal/commit/75d16dcd03b2d8860e1030d69fd29b2234b907d3)
